/* eslint-disable */
// AUTO-GENERATED by scripts/extract-projects.mjs — do not edit manually
// Re-run: npm run extract:projects

export const projectsMeta = {
  "extractedAt": "2026-05-23T12:24:34.879Z",
  "workspaceRoot": "/Users/rohit_007/Portfolio-Website",
  "gitRemotesDetected": [
    {
      "path": ".",
      "repositoryUrl": "https://github.com/MoncyDev/Portfolio-Website",
      "host": "github"
    }
  ],
  "sourceRepositoryUrls": [],
  "imagesFound": [
    "/images/express.webp",
    "/images/hp_sprocket.png",
    "/images/javascript.webp",
    "/images/kodak_step.png",
    "/images/mongo.webp",
    "/images/mysql.webp",
    "/images/next.webp",
    "/images/next1.webp",
    "/images/next2.webp",
    "/images/nextBL.webp",
    "/images/node.webp",
    "/images/node2.webp",
    "/images/placeholder.webp",
    "/images/react.webp",
    "/images/react2.webp",
    "/images/typescript.webp"
  ]
} as const;

export const projects = [
  {
    "id": "portfolio-website",
    "num": "01",
    "name": "Portfolio Website",
    "category": "Web & Interactive Development",
    "status": "open-source",
    "featured": true,
    "platform": "web",
    "description": "Personal developer portfolio with immersive 3D character, GSAP scroll experiences, and a recruiter-focused showcase of mobile engineering work.",
    "contributions": [
      "Built responsive React + TypeScript UI with premium dark theme and glassmorphism",
      "Integrated Three.js / React Three Fiber for interactive 3D landing experience",
      "Implemented GSAP ScrollTrigger animations and smooth section transitions",
      "Structured modular sections for skills, career, projects, and contact"
    ],
    "technologies": [
      "React",
      "TypeScript",
      "Vite",
      "GSAP",
      "Three.js"
    ],
    "storeUrl": null,
    "repositoryUrl": "https://github.com/MoncyDev/Portfolio-Website",
    "repositoryHost": "github"
  },
  {
    "id": "hp-sprocket",
    "num": "02",
    "name": "HP Sprocket",
    "category": "Cross-Platform Mobile",
    "status": "shipped",
    "featured": true,
    "platform": "mobile",
    "description": "Built and maintained the HP Sprocket mobile application using Flutter and Native iOS, delivering reliable printer connectivity, authentication, and a polished cross-platform experience.",
    "contributions": [
      "Developed cross-platform features with Flutter and Dart for iOS and Android",
      "Integrated Firebase Auth, push notifications, and Crashlytics for stability",
      "Implemented localization, WebViews, and app permission flows",
      "Tuned performance and hardware communication for consistent printing workflows"
    ],
    "technologies": [
      "Flutter",
      "Dart",
      "Firebase",
      "Native iOS",
      "Push Notifications"
    ],
    "image": "/images/hp_sprocket.png",
    "alt": "HP Sprocket preview",
    "storeUrl": null,
    "repositoryUrl": null,
    "repositoryHost": null
  },
  {
    "id": "kodak-step-print",
    "num": "03",
    "name": "Kodak Step Print",
    "category": "Native iOS",
    "status": "shipped",
    "featured": true,
    "platform": "mobile",
    "description": "Worked on the Kodak Step Printer mobile application using Native iOS development, focusing on printer connectivity, firmware management, and advanced app functionalities.",
    "contributions": [
      "Implemented firmware update workflows for printer devices to improve performance and stability",
      "Developed advanced popup flows and custom alert logic for seamless user interactions",
      "Managed app permissions including Bluetooth, Camera, Photos, and Notifications",
      "Enhanced printer communication workflows and optimized application stability",
      "Improved UI interactions and overall app experience through efficient logic implementation"
    ],
    "technologies": [
      "Swift",
      "UIKit",
      "CoreBluetooth",
      "Xcode",
      "Firmware Updates"
    ],
    "image": "/images/kodak_step.png",
    "alt": "Kodak Step Print preview",
    "storeUrl": "https://apps.apple.com/in/app/kodak-step-prints/id1494704742",
    "repositoryUrl": null,
    "repositoryHost": null
  },
  {
    "id": "lifeprint",
    "num": "04",
    "name": "LifePrint",
    "category": "Native iOS",
    "status": "shipped",
    "featured": false,
    "platform": "mobile",
    "description": "Contributed to the development of the LifePrint mobile application using Native iOS development, focusing on UI customization, image processing, and app optimization.",
    "contributions": [
      "Implemented photo cropping and image editing functionalities for enhanced user customization",
      "Developed and customized advanced Tab Bar UI for smoother navigation and better user experience",
      "Worked on UI refinements, layout optimizations, and responsive screen adjustments",
      "Performed debugging and issue resolution to improve app stability and performance",
      "Improved application workflows and user interactions through optimized UI implementation",
      "Collaborated on feature enhancements and platform-specific Native iOS functionalities"
    ],
    "technologies": [
      "Swift",
      "UIKit",
      "Image Processing",
      "Xcode",
      "Custom UI"
    ],
    "storeUrl": "https://apps.apple.com/in/app/lifeprint-printers/id972104022",
    "repositoryUrl": null,
    "repositoryHost": null
  }
] as const;

export type GeneratedProject = (typeof projects)[number];
